apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mstest
  labels:
    app: mstest
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mstest
        tier: frontend
    spec:
      containers:
      - name: mstest
        image: gcr.io/still-bank-234915/mstest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
          - name: GCLOUD_PROJECT
            value: still-bank-234915
          - name: GCLOUD_BUCKET
            value: still-bank-234915-media
          - name: NODE_ENV
            value: production
