apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mstest
  labels:
    app: mstest
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mstest
        tier: frontend
    spec:
      containers:
      - name: mstest
        image: gcr.io/qwiklabs-gcp-773a9e33f861d70d/mstest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
          - name: GCLOUD_PROJECT
            value: qwiklabs-gcp-773a9e33f861d70d
          - name: GCLOUD_BUCKET
            value: qwiklabs-gcp-773a9e33f861d70d-media
          - name: NODE_ENV
            value: production
